<a href="https://colab.research.google.com/github/imvickykumar999/2D.np-Rubix-Cube/blob/master/2D_Rubix_Cube.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
my_list = [1,2,3,4] 
print([x+1 for x in my_list]) # add 1 to every element?

[2, 3, 4, 5]


In [ ]:
import numpy as np
arr = np.array([1,2.4,'3',4])
print(arr)

['1' '2.4' '3' '4']


In [ ]:
arr.dtype

dtype('<U32')

In [ ]:
np.zeros((2,5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
np.ones((3,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.linspace(1.3546778,1.3546779,10)

array([1.3546778 , 1.35467781, 1.35467782, 1.35467783, 1.35467784,
       1.35467786, 1.35467787, 1.35467788, 1.35467789, 1.3546779 ])

In [ ]:
np.eye(4,5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]])

In [ ]:
arr = [[1,2,3,4], [11,21,31,41], [12,22,32,42], [13,23,33,43]]
arr = np.array(arr)
arr[:,1].reshape(4,1)

array([[ 2],
       [21],
       [22],
       [23]])

In [ ]:
arr

array([[ 1,  2,  3,  4],
       [11, 21, 31, 41],
       [12, 22, 32, 42],
       [13, 23, 33, 43]])

In [ ]:
arr.sum(axis=0)

array([ 37,  68,  99, 130])

In [ ]:
arr.sum(axis=1) # sum of [ 1,  2,  3,  4]

array([ 10, 104, 108, 112])

In [ ]:
arr.mean(axis=0)

array([ 9.25, 17.  , 24.75, 32.5 ])

In [ ]:
# excercise # get this array wwithout using np.array # create an array 

arr = [[ 1, 2, 3, 4, 5],
[ 6, 7, 8, 9, 10],
[11, 12, 13, 14, 15],
[16, 17, 18, 19, 20]]

In [ ]:
np.arange(1,21).reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
[1,2]*2

[1, 2, 1, 2]

In [ ]:
np.array([0,1])/0

<ipython-input-62-f918abecc96d>:1: RuntimeWarning: divide by zero encountered in true_divide
  np.array([0,1])/0
<ipython-input-62-f918abecc96d>:1: RuntimeWarning: invalid value encountered in true_divide
  np.array([0,1])/0


array([nan, inf])

In [ ]:
np.array([1,2,3])**(.5)

array([1.        , 1.41421356, 1.73205081])

In [ ]:
np.inf, np.nan

(inf, nan)

In [ ]:
arr = np.array([1,2,5,7,5,7,2,4,7,9,0,2,7,3])
arr

array([1, 2, 5, 7, 5, 7, 2, 4, 7, 9, 0, 2, 7, 3])

In [ ]:
for i,j in enumerate(arr):
  if j == 7:
    print(i)

3
5
8
12


In [ ]:
np.where(arr==7)

(array([ 3,  5,  8, 12]),)

In [ ]:
arr2d = [[1,5,7,3], [4,7,2,4], [7,6,8,3]]
arr2d = np.array(arr2d)
arr2d

array([[1, 5, 7, 3],
       [4, 7, 2, 4],
       [7, 6, 8, 3]])

In [ ]:
np.where(arr2d==7)

(array([0, 1, 2]), array([2, 1, 0]))

In [49]:

import numpy as np

empty = np.chararray((3, 3))
red = np.chararray((3, 3))
white = np.chararray((3, 3))
green = np.chararray((3, 3))
yellow = np.chararray((3, 3))
blue = np.chararray((3, 3))
orange = np.chararray((3, 3))

empty[:] = ' '
red[:] = 'R'
white[:] = 'W'
green[:] = 'G'
yellow[:] = 'Y'
blue[:] = 'B'
orange[:] = 'O'

layer1 = np.hstack((empty, red, empty, empty))
layer2 = np.hstack((white, green, yellow, blue))
layer3 = np.hstack((empty, orange, empty, empty))

board = np.vstack((layer1, layer2, layer3))
print(board)


[[b' ' b' ' b' ' b'R' b'R' b'R' b' ' b' ' b' ' b' ' b' ' b' ']
 [b' ' b' ' b' ' b'R' b'R' b'R' b' ' b' ' b' ' b' ' b' ' b' ']
 [b' ' b' ' b' ' b'R' b'R' b'R' b' ' b' ' b' ' b' ' b' ' b' ']
 [b'W' b'W' b'W' b'G' b'G' b'G' b'Y' b'Y' b'Y' b'B' b'B' b'B']
 [b'W' b'W' b'W' b'G' b'G' b'G' b'Y' b'Y' b'Y' b'B' b'B' b'B']
 [b'W' b'W' b'W' b'G' b'G' b'G' b'Y' b'Y' b'Y' b'B' b'B' b'B']
 [b' ' b' ' b' ' b'O' b'O' b'O' b' ' b' ' b' ' b' ' b' ' b' ']
 [b' ' b' ' b' ' b'O' b'O' b'O' b' ' b' ' b' ' b' ' b' ' b' ']
 [b' ' b' ' b' ' b'O' b'O' b'O' b' ' b' ' b' ' b' ' b' ' b' ']]


In [50]:
temp = np.copy(board[4, 0:3])
board[4, 0:3] = board[4, 3:6]
board[4, 3:6] = board[4, 6:9]
board[4, 6:9] = board[4, 9:12]
board[4, 9:12] = temp
print(board)

[[b' ' b' ' b' ' b'R' b'R' b'R' b' ' b' ' b' ' b' ' b' ' b' ']
 [b' ' b' ' b' ' b'R' b'R' b'R' b' ' b' ' b' ' b' ' b' ' b' ']
 [b' ' b' ' b' ' b'R' b'R' b'R' b' ' b' ' b' ' b' ' b' ' b' ']
 [b'W' b'W' b'W' b'G' b'G' b'G' b'Y' b'Y' b'Y' b'B' b'B' b'B']
 [b'G' b'G' b'G' b'Y' b'Y' b'Y' b'B' b'B' b'B' b'W' b'W' b'W']
 [b'W' b'W' b'W' b'G' b'G' b'G' b'Y' b'Y' b'Y' b'B' b'B' b'B']
 [b' ' b' ' b' ' b'O' b'O' b'O' b' ' b' ' b' ' b' ' b' ' b' ']
 [b' ' b' ' b' ' b'O' b'O' b'O' b' ' b' ' b' ' b' ' b' ' b' ']
 [b' ' b' ' b' ' b'O' b'O' b'O' b' ' b' ' b' ' b' ' b' ' b' ']]
